---
- hosts: servers
  become: yes
  gather_facts: no
  tasks:
  - name: stop the services
    service: 
      name: "{{ item }}"
      state: stopped
    with_items:
    - docker
    - php-fpm
    - nginx
    - keepalived
    - td-agent

  - name: disable the services on boot
    service: 
      name: "{{ item }}"
      enabled: no
    with_items:
    - docker
    - php-fpm
    - nginx
    - keepalived
    - td-agent
